config/routes.rb
Geogems::Application.routes.draw do

  root :to => "trivia_items#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :trivia_items

  post '/ajaxsearch', to: 'trivia_items#ajaxsearch', as: 'ajax'
  post '/citysearch', to: 'trivia_items#ajax_city_search', as:'ajaxcity'

  get '/about', to: 'pages#about', as:'about'

  get '/sources', to: 'pages#sources', as:'sources'

  get '/relatedlinks', to: 'pages#links', as:'links'

end

app/models/trivia_item.rb
class TriviaItem < ActiveRecord::Base
  acts_as_mappable :lat_column_name => :latitude, :lng_column_name => :longitude
  
  belongs_to :category
  belongs_to :source
  belongs_to :contributor
  
  validates :city, :presence => true
  
  def self.search(params)
    if params[:zipcode].present?
      return location_search(params)
    end
    
    results = TriviaItem
    if params[:state].present?
      results = results.where("state LIKE '%#{params[:state]}%'")

    end
    if params[:city].present?
      results = results.where("city LIKE '%#{params[:city]}%'")

    end
    if params[:content].present?
      results = results.where(["lower(content) LIKE ?", "%#{params[:content]}%"])
    end

    results = results.order("city asc, state asc")

    results
  end
  
  def self.location_search(params)
    TriviaItem.paginate \
      :origin => params[:zipcode], 
      :units => :miles, 
      :order => "distance asc", 
      :conditions => "latitude is not null and longitude is not null",
      :page => params[:page]
  end

  
  def location_string
    "#{city}, #{state}"
  end

  def self.city_search(city)
      city = city.downcase
      result = TriviaItem.select('DISTINCT city, state').where("lower(city) LIKE '#{city}%'") unless city.blank?
  end
end

app/controllers/trivia_items_controller.rb
class TriviaItemsController < ApplicationController

  def index
    if params[:q]
      @trivia_items = Trivia.search(params)
      render "results"
    end
  end

  # GET /trivia_items/1
  # GET /trivia_items/1.xml
  def show
    @trivia_item = Trivia.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @trivia_item }
    end
  end

  # GET /trivia_items/new
  # GET /trivia_items/new.xml
  def new
    @trivia_item = Trivia.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trivia_item }
    end
  end

  # GET /trivia_items/1/edit
  def edit
    @trivia_item = Trivia.find(params[:id])
  end

  # POST /trivia_items
  # POST /trivia_items.xml
  def create
    @trivia_item = Trivia.new(params[:trivia_item])

    respond_to do |format|
      if @trivia_item.save
        format.html { redirect_to(@trivia_item, :notice => 'Trivia item was successfully created.') }
        format.xml  { render :xml => @trivia_item, :status => :created, :location => @trivia_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trivia_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trivia_items/1
  # PUT /trivia_items/1.xml
  def update
    @trivia_item = Trivia.find(params[:id])

    respond_to do |format|
      if @trivia_item.update_attributes(params[:trivia_item])
        format.html { redirect_to(@trivia_item, :notice => 'Trivia item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trivia_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trivia_items/1
  # DELETE /trivia_items/1.xml
  def destroy
    @trivia_item = Trivia.find(params[:id])
    @trivia_item.destroy

    respond_to do |format|
      format.html { redirect_to(trivia_items_url) }
      format.xml  { head :ok }
    end
  end

  def ajaxsearch
    if(params[:city]=='false')
      @trivia_items = Trivia.select('DISTINCT trim(city) as city, state').where("state = ?", params[:state])
      @markers = '['
      @trivia_items.group_by(&:location_string).each do |location, trivia_items|
        trivia_items.each do |trivia_item|
          if(trivia_item.trivia_count>=1 && trivia_item.trivia_count <=2)
            marker_image = '/images/pin_3.png'
          elsif(trivia_item.trivia_count>2 && trivia_item.trivia_count<=5)
            marker_image = '/images/pin_2.png'
          else
            marker_image = '/images/pin_1.png'
          end
          @markers+="{\"address\":\""+trivia_item.city.tr("\"","\'")+" ,"+trivia_item.state+" ,"+trivia_item.country+"\", \"data\":{\"city\":\""+trivia_item.city.tr("\"","\'")+"\", \"state\":\""+trivia_item.state+"\", \"trivia\":\"#{trivia_item.trivia_count.to_s}\"}, \"options\":{\"icon\":\"#{marker_image}\"} }, "
        end
      end
      @markers += '{}]'
      render :partial=> "search_nearby"
    else
      @city = params[:city]
      @state = params[:state]
      @trivia_items = Trivia.where("city = ? AND state = ?",@city, @state)

      render :partial=> "ajaxsearch"
    end
  end

  def ajax_city_search
    if(params[:city].present?)
      @result = Trivia.city_search(params[:city]).order("city asc")

      render :partial=>"city_autofil"
    end
  end
end

app/helpers/trivia_items_helper.rb
module TriviaItemsHelper
end

app/views/trivia_items/_ajaxsearch.html.haml
- @trivia_items.group_by(&:location_string).each do |location, trivia_items|
  .location= location
  %ul
    - trivia_items.each do |trivia_item|
      - if (trivia_item.category && trivia_item.category.name == "Funny Name")
        %li{:style=>'list-style-type: none;'}
          .content= trivia_item.content
          - if trivia_item.category && trivia_item.category.name == "Funny Name"
            = '(funny name)'
      - else
        %li[trivia_item]
          .content= trivia_item.content
          - if trivia_item.category && trivia_item.category.name == "Funny Name"
            = 'funny name'
          - if trivia_item.source
            .source
              %i
                = trivia_item.source.title

app/views/trivia_items/_city_autofil.html.erb
<ul id="searched_cities" class="dropdown-menu">
  <% if @result.empty? %>
        <center>- No results-</center>
  <% else%>
      <% @result.each do |city| %>
        <li data-value="<%= city.state %>"><%= "#{city.location_string}" %></li>
      <% end %>
  <% end %>
</ul>

app/views/trivia_items/_footer.html.haml
.mar-top-20.footer
  %h1
    Know any good GeoGems? Email
    %a{:href=>'mailto:geogems@gmail.com'} geogems@gmail.com
  %p Subject: GeoGems &nbsp;&nbsp;Include: city, state, description of your GeoGem -- and whether you would like it attributed to you if used.<br> <b>Thanks!</b>
  .center
    %ul
      %li
        %a{:href=>'about'} About Us
      %li
        %a{:href=>'sources'} Sources
      %li
        %a{:href=>'/'} Related Links

app/views/trivia_items/_form.html.erb
<%= form_for(@trivia_item) do |f| %>
  <% if @trivia_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trivia_item.errors.count, "error") %> prohibited this trivia_item from being saved:</h2>

      <ul>
      <% @trivia_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name, :include_blank => true, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.collection_select :source_id, Source.all, :id, :title, :include_blank => true, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :contributor %><br />
    <%= f.collection_select :contributor_id, Contributor.all, :id, :name, :include_blank => true, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trivia_items/_search_form.html.haml
- form_tag "/", :method => 'get' do
  = hidden_field_tag "q", "1"

  .fr.relative
    %p
      = text_field_tag :city, "", :title => "Search City...", :placeholder =>'Enter city name', :id =>'city', :autocomplete=>"off"
      = select_tag( :state, options_for_select(State::STATES.unshift(["Select a state",""])), :id=>'state')
      = submit_tag "Search"
      #city_result.absolute{:style=>'display:none'}
  .clear

  .align-right.submit-btn
    .align-left.fl.text-search-link
      %a{:href=>'http://geogems.herokuapp.com/'} go to GeoGems in Lists (no map)
    .clear

app/views/trivia_items/_search_nearby.html.haml
= raw @markers

app/views/trivia_items/edit.html.erb
<h1>Editing trivia_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @trivia_item %> |
<%= link_to 'Back', trivia_items_path %>

app/views/trivia_items/index.html.haml
.wrapper.content
  .map-container.relative
    #map_canvas_home.grid70.fl
      %img{:src=>'images/usa_default.png', :style=>'width:100%;height:100%'}
    #trivia_home.grid30.mar-left-20.fl.relative
      .trivia_content
        %h3 Enter your search query above
        .clear

    .clear

app/views/trivia_items/new.html.erb
<h1>New trivia_item</h1>

<%= render 'form' %>

<%= link_to 'Back', trivia_items_path %>

app/views/trivia_items/results.html.haml
- markers = ''
.wrapper.content
  .map-container.relative
    #loader.absolute{:style=>'display:none'}
      %img{:src=>'images/loading_icon.gif'}
    #map_canvas.grid70.fl

    #trivia.grid30.mar-left-20.fl.relative
      .trivia_content
        - if @trivia_items.empty?
          Nothing found.
        - else
          %h3.mar-none Click on any marker to view its GeoGems
          - @trivia_items.group_by(&:location_string).each do |location, trivia_items|
            %ul
              - trivia_items.each do |trivia_item|
                - if(trivia_item.trivia_count >= 1 && trivia_item.trivia_count<=2)
                  - marker_image = '/images/pin_3.png'
                - elsif(trivia_item.trivia_count > 2 && trivia_item.trivia_count<=5)
                  - marker_image = '/images/pin_2.png'
                - else
                  - marker_image = '/images/pin_1.png'

                - markers+='{address:"'+trivia_item.city+' ,'+trivia_item.state+' ,'+trivia_item.country+'", data:{city:"'+trivia_item.city+'", state:"'+trivia_item.state+'", trivia:"'+trivia_item.trivia_count.to_s+'",}, options:{icon: "'+marker_image+'"}},'
                -#%li[trivia_item]
                -#  .content= trivia_item.content
                -#  - if trivia_item.category && trivia_item.category.name != "Uncategorized"
                -#    .category= trivia_item.category.name
                -#  - if trivia_item.source
                -#    .source= trivia_item.source.title
                -#  - if trivia_item.contributor
                -#    .contributor= trivia_item.contributor.name
      .clear
    .clear

  %script{ :type=>'text/javascript' }
    var a = [
    = raw markers
    ]
    init_search_map(a);





-#$.each( data.markers, function(i, marker) {
-#						$('#map_canvas').gmap('addMarker', {
-#							'position': new google.maps.LatLng(marker.latitude, marker.longitude),
-#							'title': marker.title,
-#							'category': marker.category,
-#							'bounds': true
-#						}).click(function() {
-#							$('#map_canvas').gmap('openInfoWindow', { 'content': marker.content }, this);
-#						});
-#					});


-##small_search.selfclear= render "search_form"
-#
-#- if @trivia_items.empty?
-#  Nothing found.
-#
-#.trivia_items
-#  - @trivia_items.group_by(&:location_string).each do |location, trivia_items|
-#    .location= location
-#    %ul
-#      - trivia_items.each do |trivia_item|
-#        %li[trivia_item]
-#          .content= trivia_item.content
-#          - if trivia_item.category && trivia_item.category.name != "Uncategorized"
-#            .category= trivia_item.category.name
-#          - if trivia_item.source
-#            .source= trivia_item.source.title
-#          - if trivia_item.contributor
-#            .contributor= trivia_item.contributor.name
-#
-#  = will_paginate @trivia_items

app/views/trivia_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @trivia_item.content %>
</p>

<p>
  <b>Category:</b>
  <%= @trivia_item.category.try(:name) %>
</p>

<p>
  <b>Source:</b>
  <%= @trivia_item.source.try(:title) %>
</p>

<p>
  <b>Contributor:</b>
  <%= @trivia_item.contributor.try(:name) %>
</p>

<p>
  <b>City:</b>
  <%= @trivia_item.city %>
</p>

<p>
  <b>State:</b>
  <%= @trivia_item.state %>
</p>

<p>
  <b>Country:</b>
  <%= @trivia_item.country %>
</p>


<%= link_to 'Edit', edit_trivia_item_path(@trivia_item) %> |
<%= link_to 'Back', trivia_items_path %>